services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
volumes:
  postgres_data: